version: "3.9"

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  api:
    build: ./server
    ports:
      - 5000:5000
    volumes:
      - ./server:/usr/src/app
    environment:
      PORT: 5000
      MONGO_URL: mongodb://mongo_db:27017
      DB_NAME: pos_app
      ACCESS_TOKEN_SECRET: 9f4c1bd489280f2c9c9fc54dd33fd231213c319d30f174bfe5c10824635c48b4
      REFRESH_TOKEN_SECRET: d0302d419b0dc5cf129e82394be26848867a4f97850b0125c02899cbaeca8352
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
