### add a users
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "email": "sha@yopmail.com",
    "password": "123"
}

### login route
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "ni@yopmail.com",
    "password": "123"
}