### Login 
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "nikujais@yopmail.com",
    "password": "1234"
}

### Verify User 
GET http://localhost:5000/auth/verify-user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWVkZWIxNGVmZDM4OWYxZmU2NjY1YTAiLCJyb2xlIjoiQWRtaW4iLCJpYXQiOjE3MTAwOTM3NzksImV4cCI6MTcxMDA5NzM3OSwiYXVkIjoiNjVlZGViMTRlZmQzODlmMWZlNjY2NWEwIiwiaXNzIjoibmlrdWphaXMuY29tIn0.FAUz2rxu2wrBj6FKwKWJRmNbbe-CcKZQ0sgRilSO9Oo
