### Upload Profile Picture
POST http://localhost:5000/picture/upload
Content-Type: multipart/form-data

--form image=./server/language.png


### Get profile Pic
GET http://localhost:5000/picture/65da43444d6fbfc89bb93478
Content-Type: image/jpeg