### get all Role names
GET http://localhost:5000/role_list
Content-Type: application/json

### add a Role Name
POST http://localhost:5000/role_list
Content-Type: application/json

{
    "name": "aa",
    "roles": [{"id": "65d0d948126599d9c9d0cc2c", "name": "dfsdf", "status": false}],
    "status": true
}

### get one Role name
GET http://localhost:5000/role_list/65d0d902126599d9c9d0cc22
Content-Type: application/json

### Update one Role name
PUT http://localhost:5000/role_list/65d0d902126599d9c9d0cc22
Content-Type: application/json

{
    "active": true
}

### Delete one Role Name
DELETE  http://localhost:5000/role_list/65d0db4beaa0c906b3440b8c
Content-Type: application/json
